apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-server.fullname" . }}
  labels:
    app: {{ template "grpc-server.name" . }}
    tier: backend
    component: go-chi
    componentVersion: v4
    env: {{ .Values.env }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    lang: golang
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
    - port: 1323
      targetPort: 1323
      protocol: TCP
      name: http
  selector:
    app: {{ template "grpc-server.name" . }}
    tier: backend
    component: go-chi
    componentVersion: v4
    env: {{ .Values.env }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    lang: golang
