// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TodoSaveRequest struct {
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoSaveRequest) Reset()         { *m = TodoSaveRequest{} }
func (m *TodoSaveRequest) String() string { return proto.CompactTextString(m) }
func (*TodoSaveRequest) ProtoMessage()    {}
func (*TodoSaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *TodoSaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoSaveRequest.Unmarshal(m, b)
}
func (m *TodoSaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoSaveRequest.Marshal(b, m, deterministic)
}
func (m *TodoSaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoSaveRequest.Merge(m, src)
}
func (m *TodoSaveRequest) XXX_Size() int {
	return xxx_messageInfo_TodoSaveRequest.Size(m)
}
func (m *TodoSaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoSaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoSaveRequest proto.InternalMessageInfo

func (m *TodoSaveRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type TodoGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoGetRequest) Reset()         { *m = TodoGetRequest{} }
func (m *TodoGetRequest) String() string { return proto.CompactTextString(m) }
func (*TodoGetRequest) ProtoMessage()    {}
func (*TodoGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *TodoGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoGetRequest.Unmarshal(m, b)
}
func (m *TodoGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoGetRequest.Marshal(b, m, deterministic)
}
func (m *TodoGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoGetRequest.Merge(m, src)
}
func (m *TodoGetRequest) XXX_Size() int {
	return xxx_messageInfo_TodoGetRequest.Size(m)
}
func (m *TodoGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoGetRequest proto.InternalMessageInfo

func (m *TodoGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TodoListRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoListRequest) Reset()         { *m = TodoListRequest{} }
func (m *TodoListRequest) String() string { return proto.CompactTextString(m) }
func (*TodoListRequest) ProtoMessage()    {}
func (*TodoListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *TodoListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoListRequest.Unmarshal(m, b)
}
func (m *TodoListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoListRequest.Marshal(b, m, deterministic)
}
func (m *TodoListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoListRequest.Merge(m, src)
}
func (m *TodoListRequest) XXX_Size() int {
	return xxx_messageInfo_TodoListRequest.Size(m)
}
func (m *TodoListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoListRequest proto.InternalMessageInfo

func (m *TodoListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *TodoListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type TodoUpdateRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoUpdateRequest) Reset()         { *m = TodoUpdateRequest{} }
func (m *TodoUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*TodoUpdateRequest) ProtoMessage()    {}
func (*TodoUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *TodoUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoUpdateRequest.Unmarshal(m, b)
}
func (m *TodoUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoUpdateRequest.Marshal(b, m, deterministic)
}
func (m *TodoUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoUpdateRequest.Merge(m, src)
}
func (m *TodoUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_TodoUpdateRequest.Size(m)
}
func (m *TodoUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoUpdateRequest proto.InternalMessageInfo

func (m *TodoUpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TodoUpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type TodoDeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoDeleteRequest) Reset()         { *m = TodoDeleteRequest{} }
func (m *TodoDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*TodoDeleteRequest) ProtoMessage()    {}
func (*TodoDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *TodoDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoDeleteRequest.Unmarshal(m, b)
}
func (m *TodoDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoDeleteRequest.Marshal(b, m, deterministic)
}
func (m *TodoDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoDeleteRequest.Merge(m, src)
}
func (m *TodoDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_TodoDeleteRequest.Size(m)
}
func (m *TodoDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TodoDeleteRequest proto.InternalMessageInfo

func (m *TodoDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TodoResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoResponse) Reset()         { *m = TodoResponse{} }
func (m *TodoResponse) String() string { return proto.CompactTextString(m) }
func (*TodoResponse) ProtoMessage()    {}
func (*TodoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{5}
}

func (m *TodoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoResponse.Unmarshal(m, b)
}
func (m *TodoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoResponse.Marshal(b, m, deterministic)
}
func (m *TodoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoResponse.Merge(m, src)
}
func (m *TodoResponse) XXX_Size() int {
	return xxx_messageInfo_TodoResponse.Size(m)
}
func (m *TodoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodoResponse proto.InternalMessageInfo

func (m *TodoResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TodoResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type TodoListResponse struct {
	Todos                []*TodoResponse `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TodoListResponse) Reset()         { *m = TodoListResponse{} }
func (m *TodoListResponse) String() string { return proto.CompactTextString(m) }
func (*TodoListResponse) ProtoMessage()    {}
func (*TodoListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{6}
}

func (m *TodoListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoListResponse.Unmarshal(m, b)
}
func (m *TodoListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoListResponse.Marshal(b, m, deterministic)
}
func (m *TodoListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoListResponse.Merge(m, src)
}
func (m *TodoListResponse) XXX_Size() int {
	return xxx_messageInfo_TodoListResponse.Size(m)
}
func (m *TodoListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodoListResponse proto.InternalMessageInfo

func (m *TodoListResponse) GetTodos() []*TodoResponse {
	if m != nil {
		return m.Todos
	}
	return nil
}

type TodoEmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoEmptyResponse) Reset()         { *m = TodoEmptyResponse{} }
func (m *TodoEmptyResponse) String() string { return proto.CompactTextString(m) }
func (*TodoEmptyResponse) ProtoMessage()    {}
func (*TodoEmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{7}
}

func (m *TodoEmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoEmptyResponse.Unmarshal(m, b)
}
func (m *TodoEmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoEmptyResponse.Marshal(b, m, deterministic)
}
func (m *TodoEmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoEmptyResponse.Merge(m, src)
}
func (m *TodoEmptyResponse) XXX_Size() int {
	return xxx_messageInfo_TodoEmptyResponse.Size(m)
}
func (m *TodoEmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoEmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TodoEmptyResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TodoSaveRequest)(nil), "proto.TodoSaveRequest")
	proto.RegisterType((*TodoGetRequest)(nil), "proto.TodoGetRequest")
	proto.RegisterType((*TodoListRequest)(nil), "proto.TodoListRequest")
	proto.RegisterType((*TodoUpdateRequest)(nil), "proto.TodoUpdateRequest")
	proto.RegisterType((*TodoDeleteRequest)(nil), "proto.TodoDeleteRequest")
	proto.RegisterType((*TodoResponse)(nil), "proto.TodoResponse")
	proto.RegisterType((*TodoListResponse)(nil), "proto.TodoListResponse")
	proto.RegisterType((*TodoEmptyResponse)(nil), "proto.TodoEmptyResponse")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xee, 0xfe, 0x82, 0xa3, 0x54, 0x4d, 0xb5, 0x2e, 0x7b, 0x5a, 0xe2, 0xc1, 0x7a, 0xe9, 0xa1,
	0xd5, 0x43, 0x0f, 0xea, 0x45, 0xe9, 0xc5, 0x53, 0xd4, 0x07, 0xa8, 0xec, 0x14, 0x02, 0x5b, 0xb3,
	0x9a, 0x51, 0xf0, 0x8d, 0x7c, 0x4c, 0xc9, 0xa6, 0xb5, 0x09, 0x1a, 0xf0, 0x14, 0x26, 0xf3, 0xfd,
	0x24, 0xdf, 0x07, 0x40, 0xaa, 0x56, 0xe3, 0xf6, 0x4d, 0x91, 0x62, 0x59, 0x77, 0xf0, 0x33, 0xd8,
	0x7f, 0x54, 0xb5, 0x7a, 0x58, 0x7c, 0xa0, 0xc0, 0xd7, 0x77, 0xd4, 0xc4, 0x8e, 0x20, 0x23, 0x49,
	0x0d, 0x16, 0x71, 0x15, 0x8d, 0x76, 0x84, 0x1d, 0x78, 0x05, 0x7d, 0x03, 0x9c, 0x23, 0x6d, 0x70,
	0x7d, 0x88, 0x65, 0x5d, 0x44, 0x1d, 0x28, 0x96, 0x35, 0xbf, 0xb1, 0x52, 0xf7, 0x52, 0xff, 0x40,
	0x86, 0x90, 0xab, 0xe5, 0x52, 0x23, 0x75, 0xb0, 0x44, 0xac, 0x27, 0x63, 0xd1, 0xc8, 0x95, 0xa4,
	0xce, 0x22, 0x11, 0x76, 0xe0, 0x33, 0x38, 0x34, 0x02, 0x4f, 0x6d, 0xbd, 0x20, 0x0c, 0xb8, 0x04,
	0x5e, 0x77, 0x6a, 0xa9, 0xb7, 0xd8, 0x60, 0x90, 0xca, 0x2f, 0x60, 0xcf, 0x80, 0x04, 0xea, 0x56,
	0xbd, 0x68, 0xfc, 0xa7, 0xf4, 0x15, 0x1c, 0x6c, 0xbf, 0xb5, 0x66, 0x9e, 0x43, 0x66, 0xa2, 0xd4,
	0x45, 0x54, 0x25, 0xa3, 0xdd, 0xc9, 0xc0, 0x66, 0x3a, 0x76, 0xd5, 0x85, 0x45, 0xf0, 0x81, 0x7d,
	0xd9, 0xdd, 0xaa, 0xa5, 0xcf, 0xcd, 0x6e, 0xf2, 0x15, 0x43, 0x6a, 0x6e, 0xd9, 0x25, 0xa4, 0x26,
	0x7a, 0x36, 0x74, 0x14, 0x9c, 0x2e, 0xca, 0xbf, 0x94, 0x79, 0x8f, 0x4d, 0x21, 0x99, 0x23, 0xb1,
	0x63, 0x67, 0xbb, 0x2d, 0x26, 0x44, 0x9a, 0x41, 0x6a, 0x3e, 0xe1, 0x79, 0x39, 0x65, 0x95, 0x27,
	0xbf, 0xee, 0x1d, 0x6a, 0x6e, 0x5b, 0x61, 0x85, 0x03, 0xf2, 0x8a, 0x0a, 0xb9, 0x5e, 0x43, 0x6e,
	0x5b, 0xf1, 0xa8, 0x5e, 0x51, 0xa5, 0xbb, 0xf1, 0x82, 0xe2, 0xbd, 0xe7, 0xbc, 0x5b, 0x4d, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x7c, 0x26, 0x04, 0xbc, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	Save(ctx context.Context, in *TodoSaveRequest, opts ...grpc.CallOption) (*TodoResponse, error)
	Get(ctx context.Context, in *TodoGetRequest, opts ...grpc.CallOption) (*TodoResponse, error)
	List(ctx context.Context, in *TodoListRequest, opts ...grpc.CallOption) (*TodoListResponse, error)
	Update(ctx context.Context, in *TodoUpdateRequest, opts ...grpc.CallOption) (*TodoResponse, error)
	Delete(ctx context.Context, in *TodoDeleteRequest, opts ...grpc.CallOption) (*TodoEmptyResponse, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) Save(ctx context.Context, in *TodoSaveRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := c.cc.Invoke(ctx, "/proto.Todo/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Get(ctx context.Context, in *TodoGetRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := c.cc.Invoke(ctx, "/proto.Todo/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) List(ctx context.Context, in *TodoListRequest, opts ...grpc.CallOption) (*TodoListResponse, error) {
	out := new(TodoListResponse)
	err := c.cc.Invoke(ctx, "/proto.Todo/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Update(ctx context.Context, in *TodoUpdateRequest, opts ...grpc.CallOption) (*TodoResponse, error) {
	out := new(TodoResponse)
	err := c.cc.Invoke(ctx, "/proto.Todo/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) Delete(ctx context.Context, in *TodoDeleteRequest, opts ...grpc.CallOption) (*TodoEmptyResponse, error) {
	out := new(TodoEmptyResponse)
	err := c.cc.Invoke(ctx, "/proto.Todo/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	Save(context.Context, *TodoSaveRequest) (*TodoResponse, error)
	Get(context.Context, *TodoGetRequest) (*TodoResponse, error)
	List(context.Context, *TodoListRequest) (*TodoListResponse, error)
	Update(context.Context, *TodoUpdateRequest) (*TodoResponse, error)
	Delete(context.Context, *TodoDeleteRequest) (*TodoEmptyResponse, error)
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoSaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Todo/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Save(ctx, req.(*TodoSaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Todo/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Get(ctx, req.(*TodoGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Todo/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).List(ctx, req.(*TodoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Todo/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Update(ctx, req.(*TodoUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Todo/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).Delete(ctx, req.(*TodoDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _Todo_Save_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Todo_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Todo_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Todo_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Todo_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
