apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-api.fullname" . }}
  labels:
    app: {{ template "web-api.name" . }}
    tier: backend
    component: nginx
    env: {{ .Values.env }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "web-api.name" . }}
    tier: backend
    component: nginx
    env: {{ .Values.env }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
