apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bff-server.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "bff-server.name" . }}
      tier: backend
      component: go-chi
      componentVersion: v4
      env: {{ .Values.env }}
      heritage: {{ .Release.Service }}
      namespace: {{ .Release.Namespace }}
      lang: golang
  template:
    metadata:
      labels:
        app: {{ template "bff-server.name" . }}
        tier: backend
        component: go-chi
        componentVersion: v4
        env: {{ .Values.env }}
        heritage: {{ .Release.Service }}
        namespace: {{ .Release.Namespace }}
        lang: golang
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 1323
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
          - name: APP_ENVIRONMENT
            value: "{{ .Values.env }}"
          - name: GRPC_TARGETADDRESS
            value: "{{ .Values.grpc.targetAddress }}"
          - name: GRPC_TIMEOUTMILLIS
            value: "{{ .Values.grpc.timeoutMillis }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
