apiVersion: v1
kind: Service
metadata:
  name: {{ include "bff-server.fullname" . }}
  labels:
    app: {{ template "bff-server.name" . }}
    tier: backend
    component: go-chi
    componentVersion: v4
    env: {{ .Values.env }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    lang: golang
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1323
      protocol: TCP
      name: http
  selector:
    app: {{ template "bff-server.name" . }}
    tier: backend
    component: go-chi
    componentVersion: v4
    env: {{ .Values.env }}
    heritage: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
    lang: golang
