-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 11:13:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema try-bff
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema try-bff
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rdbms` DEFAULT CHARACTER SET utf8 ;
USE `rdbms` ;

-- -----------------------------------------------------
-- Table `rdbms`.`todo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rdbms`.`todo` (
  `id` VARCHAR(128) NOT NULL,
  `title` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
