# Default values for grpc-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: taguch1/grpc-server
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 50051

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 600m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
